export enum ErrorCode {
  DUPLICATE_NAME = "DUPLICATE_NAME",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_USERNAME_OR_PASSWORD = "INVALID_USERNAME_OR_PASSWORD",
  NOT_FOUND_USER = "NOT_FOUND_USER",
  DUPLICATE_BROADCAST_DATE = "DUPLICATE_BROADCAST_DATE",
}
